add section
CoreX20/git-async pull request #2
Opened 2024-03-28 17:19 UTC by ardyanandakirana

2024-03-28 17:32 UTC, CoreX20 requested changes

2024-03-28 17:32 UTC, CoreX20 commented on index.html
> +    <div class="main-section pt-md-5" style="background-color: #f1f3ff">
change background color to : #e5e5e5

2024-03-28 19:14 UTC, amiqbal7 reviewed
change button color

2024-03-28 19:14 UTC, amiqbal7 commented on index.html
> +            <a href="#" class="btn btn-success">Mulai Sewa Mobil</a>
change button color to primary

2024-03-29 01:51 UTC, ardyanandakirana commented on index.html
> +    <div class="main-section pt-md-5" style="background-color: #f1f3ff">
done

2024-03-29 01:51 UTC, ardyanandakirana commented on index.html
> +            <a href="#" class="btn btn-success">Mulai Sewa Mobil</a>
done

2024-03-29 03:18 UTC, CoreX20 approved these changes

2024-03-29 03:20 UTC, merged